export const villesTunisie = [
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Bizerte",
    "Gabès",
    "Ariana",
    "Gafsa",
    "Monastir",
    "Ben Arous",
    "Kasserine",
    "Nabeul",
    "Médenine",
    "Kebili",
    "Tataouine",
    "Mahdia",
    "Manouba",
    "Siliana",
    "Jendouba",
    "Tozeur",
    "Kef",
    "Zaghouan",
    "Kébili",
    "Kélibia"
];